### PR TITLE
Erlport dependency version changed

### PR DESCRIPTION
**Pull request by KimSangYeon-DGU**
Current erlport version cannot be compiled in Erlang/OTP21. And I fixed the problem by upgrading the version.

### CODE REVIEW

**Comment by KimSangYeon-DGU** [comment]
@zoq 
I think this is a temporary solution. Why don't I make a FAQ on README instead?

**Comment by zoq** [comment]
Don't mind to use a specific version and a FAQ sounds good. If you like I can merge the changes in, just let me know.

**Comment by KimSangYeon-DGU** [comment]
Yes, I will try it.

**Comment by KimSangYeon-DGU** [comment]
@zoq 
I made a FAQ based on my experience and [the issues page](https://github.com/zoq/gym_tcp_api/issues).
I think it will help users use the program more easily. 
If you don't mind, please merge it to matser branch. 
Tell me if you have any other ideas.
Thank you!!

**Comment by KimSangYeon-DGU** [comment]
I think commit is a bit messy. I will edit and request pull later.

**Pull request closed without merging**
